-- Half-time markets (football halves, basketball first half) and player
-- over/under markets. Adding enum values is non-destructive.
ALTER TYPE "MarketType" ADD VALUE 'HALF_TIME_RESULT';
ALTER TYPE "MarketType" ADD VALUE 'FIRST_HALF_HANDICAP';
ALTER TYPE "MarketType" ADD VALUE 'FIRST_HALF_TOTAL_GOALS';
ALTER TYPE "MarketType" ADD VALUE 'SECOND_HALF_RESULT';
ALTER TYPE "MarketType" ADD VALUE 'SECOND_HALF_TOTAL_GOALS';
ALTER TYPE "MarketType" ADD VALUE 'FIRST_HALF_WINNER';
ALTER TYPE "MarketType" ADD VALUE 'FIRST_HALF_SPREAD';
ALTER TYPE "MarketType" ADD VALUE 'FIRST_HALF_TOTAL_POINTS';
ALTER TYPE "MarketType" ADD VALUE 'PLAYER_POINTS';
ALTER TYPE "MarketType" ADD VALUE 'PLAYER_REBOUNDS';
ALTER TYPE "MarketType" ADD VALUE 'PLAYER_ASSISTS';
