"""Initiales Schema

Revision ID: 730a41088276
Revises:
Create Date: 2026-09-07 13:07:47.216993
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alerts",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("sport", sa.String(length=16), nullable=False),
        sa.Column("market_key", sa.String(length=96), nullable=False),
        sa.Column("market_label", sa.String(length=128), nullable=False),
        sa.Column("selection_key", sa.String(length=96), nullable=False),
        sa.Column("selection_label", sa.String(length=128), nullable=False),
        sa.Column("bookmaker", sa.String(length=64), nullable=False),
        sa.Column("odds", sa.Float(), nullable=False),
        sa.Column("fair_odds", sa.Float(), nullable=False),
        sa.Column("value_percent", sa.Float(), nullable=False),
        sa.Column("deviation_percent", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Integer(), nullable=False),
        sa.Column("error_score", sa.Integer(), nullable=False),
        sa.Column("bookmaker_count", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("fingerprint", sa.String(length=32), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("telegram_sent", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
        sa.UniqueConstraint("fingerprint", name=op.f("uq_alerts_fingerprint")),
    )
    op.create_index(op.f("ix_alerts_bookmaker"), "alerts", ["bookmaker"], unique=False)
    op.create_index(op.f("ix_alerts_detected_at"), "alerts", ["detected_at"], unique=False)
    op.create_index("ix_alerts_detected_kind", "alerts", ["detected_at", "kind"], unique=False)
    op.create_index(op.f("ix_alerts_event_id"), "alerts", ["event_id"], unique=False)
    op.create_index(op.f("ix_alerts_kind"), "alerts", ["kind"], unique=False)
    op.create_index(op.f("ix_alerts_sport"), "alerts", ["sport"], unique=False)
    op.create_table(
        "bookmakers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("is_exchange", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bookmakers")),
    )
    op.create_index(op.f("ix_bookmakers_key"), "bookmakers", ["key"], unique=True)
    op.create_table(
        "events",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("sport", sa.String(length=16), nullable=False),
        sa.Column("league", sa.String(length=128), nullable=True),
        sa.Column("home", sa.String(length=128), nullable=False),
        sa.Column("away", sa.String(length=128), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("score_home", sa.Integer(), nullable=True),
        sa.Column("score_away", sa.Integer(), nullable=True),
        sa.Column(
            "live_state",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "providers",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
    )
    op.create_index(op.f("ix_events_sport"), "events", ["sport"], unique=False)
    op.create_index("ix_events_sport_status", "events", ["sport", "status"], unique=False)
    op.create_index(op.f("ix_events_start_time"), "events", ["start_time"], unique=False)
    op.create_index(op.f("ix_events_status"), "events", ["status"], unique=False)
    op.create_index(op.f("ix_events_updated_at"), "events", ["updated_at"], unique=False)
    op.create_table(
        "provider_health",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("connected_since", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("messages", sa.BigInteger(), nullable=False),
        sa.Column("quotes", sa.BigInteger(), nullable=False),
        sa.Column("errors", sa.Integer(), nullable=False),
        sa.Column("reconnects", sa.Integer(), nullable=False),
        sa.Column("rate_limit_remaining", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Float(), nullable=True),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_health")),
    )
    op.create_index(
        op.f("ix_provider_health_provider"), "provider_health", ["provider"], unique=True
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("first_name", sa.String(length=64), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_telegram_id"), "users", ["telegram_id"], unique=True)
    op.create_table(
        "markets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("market_key", sa.String(length=96), nullable=False),
        sa.Column("market_type", sa.String(length=32), nullable=False),
        sa.Column("line", sa.Float(), nullable=True),
        sa.Column("period", sa.String(length=24), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_markets_event_id_events"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_markets")),
        sa.UniqueConstraint("event_id", "market_key", name="uq_markets_event_market"),
    )
    op.create_index(op.f("ix_markets_event_id"), "markets", ["event_id"], unique=False)
    op.create_index(op.f("ix_markets_market_type"), "markets", ["market_type"], unique=False)
    op.create_table(
        "user_settings",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("min_value_percent", sa.Float(), nullable=False),
        sa.Column("min_outlier_percent", sa.Float(), nullable=False),
        sa.Column("min_odds", sa.Float(), nullable=False),
        sa.Column("max_odds", sa.Float(), nullable=False),
        sa.Column("min_bookmakers", sa.Integer(), nullable=False),
        sa.Column("min_confidence", sa.Integer(), nullable=False),
        sa.Column("cooldown_seconds", sa.Integer(), nullable=False),
        sa.Column(
            "sports",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "markets",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("live_enabled", sa.Boolean(), nullable=False),
        sa.Column("prematch_enabled", sa.Boolean(), nullable=False),
        sa.Column("paused", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_settings_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_settings")),
    )
    op.create_table(
        "selections",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("market_id", sa.Integer(), nullable=False),
        sa.Column("selection_key", sa.String(length=96), nullable=False),
        sa.Column("label", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["market_id"],
            ["markets.id"],
            name=op.f("fk_selections_market_id_markets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_selections")),
        sa.UniqueConstraint("market_id", "selection_key", name="uq_selections_market_selection"),
    )
    op.create_index(op.f("ix_selections_market_id"), "selections", ["market_id"], unique=False)
    op.create_table(
        "odds_changes",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("selection_id", sa.Integer(), nullable=False),
        sa.Column("bookmaker_id", sa.Integer(), nullable=False),
        sa.Column("old_price", sa.Float(), nullable=True),
        sa.Column("new_price", sa.Float(), nullable=False),
        sa.Column("delta_percent", sa.Float(), nullable=True),
        sa.Column("elapsed_seconds", sa.Float(), nullable=True),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["bookmaker_id"],
            ["bookmakers.id"],
            name=op.f("fk_odds_changes_bookmaker_id_bookmakers"),
        ),
        sa.ForeignKeyConstraint(
            ["selection_id"],
            ["selections.id"],
            name=op.f("fk_odds_changes_selection_id_selections"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_odds_changes")),
    )
    op.create_index(
        "ix_odds_changes_selection_ts", "odds_changes", ["selection_id", "ts"], unique=False
    )
    op.create_index(op.f("ix_odds_changes_ts"), "odds_changes", ["ts"], unique=False)
    op.create_table(
        "odds_snapshots",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("selection_id", sa.Integer(), nullable=False),
        sa.Column("bookmaker_id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("suspended", sa.Boolean(), nullable=False),
        sa.Column("liquidity", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bookmaker_id"],
            ["bookmakers.id"],
            name=op.f("fk_odds_snapshots_bookmaker_id_bookmakers"),
        ),
        sa.ForeignKeyConstraint(
            ["selection_id"],
            ["selections.id"],
            name=op.f("fk_odds_snapshots_selection_id_selections"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_odds_snapshots")),
    )
    op.create_index(
        "ix_odds_snapshots_selection_ts", "odds_snapshots", ["selection_id", "ts"], unique=False
    )
    op.create_index("ix_odds_snapshots_ts", "odds_snapshots", ["ts"], unique=False)
    # ### end Alembic commands ###

    # Zeitreihen wachsen streng monoton -> BRIN ist hier um Größenordnungen
    # kleiner als ein B-Tree und für Zeitfenster-Abfragen völlig ausreichend.
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_odds_snapshots_ts_brin "
        "ON odds_snapshots USING brin (ts) WITH (pages_per_range = 32)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_odds_changes_ts_brin "
        "ON odds_changes USING brin (ts) WITH (pages_per_range = 32)"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_odds_changes_ts_brin")
    op.execute("DROP INDEX IF EXISTS ix_odds_snapshots_ts_brin")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_odds_snapshots_ts", table_name="odds_snapshots")
    op.drop_index("ix_odds_snapshots_selection_ts", table_name="odds_snapshots")
    op.drop_table("odds_snapshots")
    op.drop_index(op.f("ix_odds_changes_ts"), table_name="odds_changes")
    op.drop_index("ix_odds_changes_selection_ts", table_name="odds_changes")
    op.drop_table("odds_changes")
    op.drop_index(op.f("ix_selections_market_id"), table_name="selections")
    op.drop_table("selections")
    op.drop_table("user_settings")
    op.drop_index(op.f("ix_markets_market_type"), table_name="markets")
    op.drop_index(op.f("ix_markets_event_id"), table_name="markets")
    op.drop_table("markets")
    op.drop_index(op.f("ix_users_telegram_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_provider_health_provider"), table_name="provider_health")
    op.drop_table("provider_health")
    op.drop_index(op.f("ix_events_updated_at"), table_name="events")
    op.drop_index(op.f("ix_events_status"), table_name="events")
    op.drop_index(op.f("ix_events_start_time"), table_name="events")
    op.drop_index("ix_events_sport_status", table_name="events")
    op.drop_index(op.f("ix_events_sport"), table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_bookmakers_key"), table_name="bookmakers")
    op.drop_table("bookmakers")
    op.drop_index(op.f("ix_alerts_sport"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_kind"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_event_id"), table_name="alerts")
    op.drop_index("ix_alerts_detected_kind", table_name="alerts")
    op.drop_index(op.f("ix_alerts_detected_at"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_bookmaker"), table_name="alerts")
    op.drop_table("alerts")
    # ### end Alembic commands ###
