import { createHmac, timingSafeEqual } from 'node:crypto';

/**
 * Minimal HS256 JWT implementation.
 *
 * Written by hand rather than pulled from a library so the algorithm is pinned
 * at both ends: the header is generated by us and the verifier rejects anything
 * that is not exactly `{"alg":"HS256","typ":"JWT"}`. That closes the classic
 * `alg: none` and RS256->HS256 confusion attacks by construction.
 */

const HEADER = Buffer.from(JSON.stringify({ alg: 'HS256', typ: 'JWT' })).toString('base64url');

export interface JwtPayload {
  sub: string;
  sid: string;
  role: string;
  iat: number;
  exp: number;
  iss: string;
  typ: 'access' | 'refresh';
  [key: string]: unknown;
}

export class JwtError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'JwtError';
  }
}

function sign(secret: string, data: string): string {
  return createHmac('sha256', secret).update(data).digest('base64url');
}

export function signJwt(
  secret: string,
  payload: Omit<JwtPayload, 'iat' | 'exp'> & { iat?: number },
  ttlSeconds: number,
): string {
  const now = payload.iat ?? Math.floor(Date.now() / 1000);
  const full: JwtPayload = { ...payload, iat: now, exp: now + ttlSeconds } as JwtPayload;
  const body = Buffer.from(JSON.stringify(full)).toString('base64url');
  const data = `${HEADER}.${body}`;
  return `${data}.${sign(secret, data)}`;
}

export function verifyJwt(secret: string, token: string, expectedIssuer: string): JwtPayload {
  const parts = token.split('.');
  if (parts.length !== 3) throw new JwtError('Malformed token');
  const [header, body, signature] = parts as [string, string, string];

  if (header !== HEADER) throw new JwtError('Unsupported token header');

  const expected = sign(secret, `${header}.${body}`);
  const a = Buffer.from(expected);
  const b = Buffer.from(signature);
  if (a.length !== b.length || !timingSafeEqual(a, b)) {
    throw new JwtError('Invalid token signature');
  }

  let payload: JwtPayload;
  try {
    payload = JSON.parse(Buffer.from(body, 'base64url').toString('utf8')) as JwtPayload;
  } catch {
    throw new JwtError('Malformed token payload');
  }

  const now = Math.floor(Date.now() / 1000);
  if (typeof payload.exp !== 'number' || payload.exp <= now)
    throw new JwtError('Token has expired');
  if (typeof payload.iat !== 'number' || payload.iat > now + 60)
    throw new JwtError('Token is not yet valid');
  if (payload.iss !== expectedIssuer) throw new JwtError('Token issuer mismatch');
  if (typeof payload.sub !== 'string' || payload.sub.length === 0)
    throw new JwtError('Token subject missing');

  return payload;
}

/** Parses `15m`, `2h`, `7d`, `90s` or a plain number of seconds. */
export function parseTtl(value: string): number {
  const match = /^(\d+)\s*([smhd])?$/.exec(value.trim());
  if (!match) throw new Error(`Invalid TTL: ${value}`);
  const amount = Number(match[1]);
  switch (match[2]) {
    case 'm':
      return amount * 60;
    case 'h':
      return amount * 3600;
    case 'd':
      return amount * 86400;
    default:
      return amount;
  }
}
