import type { CasinoGameType, CasinoTheme } from '@storm-bet/types';

/**
 * Provider-neutral casino contract. The built-in MockCasinoProvider runs every
 * game on this server with play money. A licensed external supplier would
 * implement the same interface: its catalogue is synced into the database,
 * createDemoSession returns its launch URL, and its rounds reach the wallet
 * through a server-to-server callback instead of the built-in engines.
 */
export interface ProviderCasinoGame {
  externalId: string;
  slug: string;
  name: string;
  type: CasinoGameType;
  categories: string[];
  description: string;
  minStake: number;
  maxStake: number;
  rtp: number;
  theme: CasinoTheme;
  isFeatured: boolean;
  isNew: boolean;
  sortOrder: number;
}

export interface ProviderCasinoCategory {
  key: string;
  name: string;
  sortOrder: number;
}

export type CasinoLaunch = { kind: 'internal' } | { kind: 'iframe'; url: string };

export interface CasinoProvider {
  readonly key: string;
  readonly name: string;
  /** True for games and outcomes generated by this platform (play money only). */
  readonly isSimulated: boolean;
  /** Rounds are decided by the built-in engines on this server. */
  readonly serverRounds: boolean;

  getGames(): Promise<ProviderCasinoGame[]>;
  getGame(externalId: string): Promise<ProviderCasinoGame | null>;
  getCategories(): Promise<ProviderCasinoCategory[]>;
  createDemoSession(input: {
    sessionId: string;
    userId: string;
    gameExternalId: string;
  }): Promise<CasinoLaunch>;
  closeSession(sessionId: string): Promise<void>;
}
